version: "1"
services:
  seq:
    image: datalust/seq:5.1
    restart: always
    ports:
      - "5342:80"
    environment:
      ACCEPT_EULA: "Y"
      SEQ_LICENSE: "sua_chave_de_licenca_aqui"
      SEQ_ADMIN_PASSWORD: "Senha@123"
    volumes:
      - seq_data:/var/lib/seq

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "AluguelMoto_Dev"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]

  db-init:
    image: postgres:13
    depends_on:
      - postgres
    environment:
      PGPASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    entrypoint: |
      bash -c "
      until pg_isready -h postgres -U postgres; do
        echo 'Waiting for PostgreSQL to be ready...'
        sleep 1
      done
      psql -h postgres -U postgres -d AluguelMoto_Dev -f /docker-entrypoint-initdb.d/init.sql
      "

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - TMPDIR=/tmp/localstack_tmp
    volumes:
      - "localstack_tmp:/tmp/localstack_tmp"

  aws-cli:
    image: amazon/aws-cli:latest
    volumes:
      - localstack_tmp:/tmp/localstack_tmp
    entrypoint: ["/bin/sh", "-c", "while sleep 1000; do :; done"]

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5532:8080"
      - "443:443"
    depends_on:
      - rabbitmq
      - postgres
      - db-init
      - seq
      - localstack
      - aws-cli
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      AWS__SERVICEURL: "http://localstack:4566"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"

volumes:
  seq_data:
  rabbitmq_data:
  postgres_data:
  localstack_tmp:
