--
-- PostgreSQL database dump
--

-- Dumped from database version 13.15 (Debian 13.15-1.pgdg120+1)
-- Dumped by pg_dump version 16.3

-- Started on 2024-06-14 11:51:28

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 209 (class 1259 OID 16555)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 16553)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 201 (class 1259 OID 16521)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 16583)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 16581)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 16596)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 16609)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16627)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 16568)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "Name" character varying(100) NOT NULL,
    "BirthDate" timestamp with time zone,
    "RegisterDate" timestamp with time zone NOT NULL,
    "CNPJ" character varying(14),
    "CNHNumber" character varying(15),
    "CNHTypeId" integer,
    "PossuiImagem" boolean NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 16531)
-- Name: CNHType; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CNHType" (
    "Id" integer NOT NULL,
    "Description" character varying(10) NOT NULL
);


ALTER TABLE public."CNHType" OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 16529)
-- Name: CNHType_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CNHType" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CNHType_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 16538)
-- Name: Motorcycle; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Motorcycle" (
    "Id" character varying(255) NOT NULL,
    "Year" integer NOT NULL,
    "Model" character varying(100) NOT NULL,
    "Plate" character varying(100) NOT NULL
);


ALTER TABLE public."Motorcycle" OWNER TO postgres;



--
-- TOC entry 207 (class 1259 OID 16545)
-- Name: Plan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Plan" (
    "Id" integer NOT NULL,
    "Day" integer NOT NULL,
    "CostPerDay" numeric NOT NULL,
    "PercentageFine" numeric NOT NULL
);


ALTER TABLE public."Plan" OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 16543)
-- Name: Plan_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Plan" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Plan_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16642)
-- Name: Rental; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Rental" (
    "Id" character varying(255) NOT NULL,
    "UserId" character varying(255) NOT NULL,
    "PlanId" integer NOT NULL,
    "RegiterDate" timestamp with time zone NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL
);


ALTER TABLE public."Rental" OWNER TO postgres;


--
-- TOC entry 200 (class 1259 OID 16447)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3122 (class 0 OID 16555)
-- Dependencies: 209
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetRoleClaims" ("Id", "RoleId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- TOC entry 3114 (class 0 OID 16521)
-- Dependencies: 201
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") FROM stdin;
\.


--
-- TOC entry 3125 (class 0 OID 16583)
-- Dependencies: 212
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserClaims" ("Id", "UserId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- TOC entry 3126 (class 0 OID 16596)
-- Dependencies: 213
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserLogins" ("LoginProvider", "ProviderKey", "ProviderDisplayName", "UserId") FROM stdin;
\.


--
-- TOC entry 3127 (class 0 OID 16609)
-- Dependencies: 214
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserRoles" ("UserId", "RoleId") FROM stdin;
\.


--
-- TOC entry 3128 (class 0 OID 16627)
-- Dependencies: 215
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserTokens" ("UserId", "LoginProvider", "Name", "Value") FROM stdin;
\.


--
-- TOC entry 3123 (class 0 OID 16568)
-- Dependencies: 210
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUsers" ("Id", "Name", "BirthDate", "RegisterDate", "CNPJ", "CNHNumber", "CNHTypeId", "PossuiImagem", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
\.


--
-- TOC entry 3116 (class 0 OID 16531)
-- Dependencies: 203
-- Data for Name: CNHType; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CNHType" ("Id", "Description") FROM stdin;
\.


--
-- TOC entry 3118 (class 0 OID 16538)
-- Dependencies: 205
-- Data for Name: Motorcycle; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Motorcycle" ("Id", "Year", "Model", "Plate") FROM stdin;
\.


--
-- TOC entry 3120 (class 0 OID 16545)
-- Dependencies: 207
-- Data for Name: Plan; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Plan" ("Id", "Day", "CostPerDay", "PercentageFine") FROM stdin;
\.


--
-- TOC entry 3130 (class 0 OID 16642)
-- Dependencies: 217
-- Data for Name: Rental; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Rental" ("Id", "UserId", "PlanId", "RegiterDate", "StartDate", "EndDate") FROM stdin;
\.


--
-- TOC entry 3113 (class 0 OID 16447)
-- Dependencies: 200
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240612151327_Initial	8.0.3
20240612182335_Message	8.0.3
20240614145004_initial	8.0.3
\.


--
-- TOC entry 3137 (class 0 OID 0)
-- Dependencies: 208
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- TOC entry 3138 (class 0 OID 0)
-- Dependencies: 211
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- TOC entry 3139 (class 0 OID 0)
-- Dependencies: 202
-- Name: CNHType_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."CNHType_Id_seq"', 1, false);


--
-- TOC entry 3140 (class 0 OID 0)
-- Dependencies: 204
-- Name: Motorcycle_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Motorcycle_Id_seq"', 1, false);


--
-- TOC entry 3141 (class 0 OID 0)
-- Dependencies: 206
-- Name: Plan_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Plan_Id_seq"', 1, false);


--
-- TOC entry 3142 (class 0 OID 0)
-- Dependencies: 216
-- Name: Rental_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Rental_Id_seq"', 1, false);


--
-- TOC entry 2951 (class 2606 OID 16562)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 2941 (class 2606 OID 16528)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 2961 (class 2606 OID 16590)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 2964 (class 2606 OID 16603)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 2967 (class 2606 OID 16616)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 2969 (class 2606 OID 16634)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 2957 (class 2606 OID 16575)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 2944 (class 2606 OID 16535)
-- Name: CNHType PK_CNHType; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CNHType"
    ADD CONSTRAINT "PK_CNHType" PRIMARY KEY ("Id");


--
-- TOC entry 2946 (class 2606 OID 16542)
-- Name: Motorcycle PK_Motorcycle; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Motorcycle"
    ADD CONSTRAINT "PK_Motorcycle" PRIMARY KEY ("Id");


--
-- TOC entry 2948 (class 2606 OID 16552)
-- Name: Plan PK_Plan; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Plan"
    ADD CONSTRAINT "PK_Plan" PRIMARY KEY ("Id");


--
-- TOC entry 2973 (class 2606 OID 16646)
-- Name: Rental PK_Rental; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Rental"
    ADD CONSTRAINT "PK_Rental" PRIMARY KEY ("Id");


--
-- TOC entry 2939 (class 2606 OID 16469)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 2952 (class 1259 OID 16662)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 2949 (class 1259 OID 16657)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 2959 (class 1259 OID 16659)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 2962 (class 1259 OID 16660)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 2965 (class 1259 OID 16661)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 2953 (class 1259 OID 16663)
-- Name: IX_AspNetUsers_CNHNumber; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_AspNetUsers_CNHNumber" ON public."AspNetUsers" USING btree ("CNHNumber");


--
-- TOC entry 2954 (class 1259 OID 16664)
-- Name: IX_AspNetUsers_CNHTypeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUsers_CNHTypeId" ON public."AspNetUsers" USING btree ("CNHTypeId");


--
-- TOC entry 2955 (class 1259 OID 16665)
-- Name: IX_AspNetUsers_CNPJ; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_AspNetUsers_CNPJ" ON public."AspNetUsers" USING btree ("CNPJ");


--
-- TOC entry 2970 (class 1259 OID 16667)
-- Name: IX_Rental_PlanId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Rental_PlanId" ON public."Rental" USING btree ("PlanId");


--
-- TOC entry 2971 (class 1259 OID 16668)
-- Name: IX_Rental_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Rental_UserId" ON public."Rental" USING btree ("UserId");


--
-- TOC entry 2942 (class 1259 OID 16658)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 2958 (class 1259 OID 16666)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 2974 (class 2606 OID 16563)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 2976 (class 2606 OID 16591)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 2977 (class 2606 OID 16604)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 2978 (class 2606 OID 16617)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 2979 (class 2606 OID 16622)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 2980 (class 2606 OID 16635)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 2975 (class 2606 OID 16576)
-- Name: AspNetUsers FK_AspNetUsers_CNHType_CNHTypeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "FK_AspNetUsers_CNHType_CNHTypeId" FOREIGN KEY ("CNHTypeId") REFERENCES public."CNHType"("Id");


--
-- TOC entry 2981 (class 2606 OID 16647)
-- Name: Rental FK_Rental_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Rental"
    ADD CONSTRAINT "FK_Rental_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 2982 (class 2606 OID 16652)
-- Name: Rental FK_Rental_Plan_PlanId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Rental"
    ADD CONSTRAINT "FK_Rental_Plan_PlanId" FOREIGN KEY ("PlanId") REFERENCES public."Plan"("Id") ON DELETE CASCADE;


--
-- TOC entry 3136 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2024-06-14 11:51:28

--
-- PostgreSQL database dump complete
--


/*Criando roles*/
INSERT INTO public."AspNetRoles" ("Id", "Name", "NormalizedName") values ('959364b1-f0fe-11ed-8b31-0242ac140004', 'Admin', 'ADMIN');
INSERT INTO public."AspNetRoles" ("Id", "Name", "NormalizedName") values ('d2017b50-84c1-45ed-ba00-9d4cf56bb998', 'Motorcyclist', 'MOTORCYCLIST');
	
/*Criando tipos de CNH*/
INSERT INTO public."CNHType"("Description") VALUES ('A');
INSERT INTO public."CNHType"("Description") VALUES ('B');
INSERT INTO public."CNHType"("Description") VALUES ('AB');

/*Criando planos*/		
INSERT INTO public."Plan"("Day", "CostPerDay", "PercentageFine") VALUES (7, 30, 20);
INSERT INTO public."Plan"("Day", "CostPerDay", "PercentageFine") VALUES (15, 28, 40);
INSERT INTO public."Plan"("Day", "CostPerDay", "PercentageFine") VALUES (30, 22, 0);
INSERT INTO public."Plan"("Day", "CostPerDay", "PercentageFine") VALUES (45, 20, 0);
INSERT INTO public."Plan"("Day", "CostPerDay", "PercentageFine") VALUES (50, 18, 0);

INSERT INTO public."AspNetUsers"(
			"Id", 
			"Name", 
			"BirthDate", 
			"RegisterDate", 
			"CNPJ", 
			"CNHNumber", 
			"CNHTypeId", 
			"UserName", 
			"NormalizedUserName", 
			"Email", 
			"NormalizedEmail", 
			"EmailConfirmed", 
			"PasswordHash", 
			"SecurityStamp", 
			"ConcurrencyStamp", 
			"PhoneNumber", 
			"PhoneNumberConfirmed", 
			"TwoFactorEnabled", 
			"LockoutEnd", 
			"LockoutEnabled", 
			"AccessFailedCount", 
			"PossuiImagem"
		) VALUES (
			'fa132a88-b684-459f-8f9c-45a2d5d8c577', 
			'Admin', 
			null, 
			'2024-06-04', 
			null, 
			null, 
			null, 
			'admin@gmail.com', 
			'ADMIN@GMAIL.COM',
			'admin@gmail.com', 
			'ADMIN@GMAIL.COM', 
			true, 
			'AQAAAAIAAYagAAAAECje3n729c1P0PCY3gHBvpbVsRMfAsWobJymt6qeB05Quub/77QhhcXi2FUtXZBqaw==', 
			'GX6GZ3R4YSMAAXH4P7RWB6OOENJ5VWMZ',
			'9055ab97-a263-4914-bbc5-03192c987486', 
			null, 
			false, 
			false, 
			null, 
			true, 
			0, 
			false
		);

INSERT INTO public."AspNetUserRoles"("UserId", "RoleId") VALUES ('fa132a88-b684-459f-8f9c-45a2d5d8c577', '959364b1-f0fe-11ed-8b31-0242ac140004');
